import got from "got"
import Koa from "koa"
import queryString from "query-string"
import requestIp from "request-ip"
import yargs from "yargs"

const job = async argv => {
  const koa = new Koa
  koa.use(context => {
    const ip = requestIp.getClientIp(context.req)
    // Payload schema: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters
    // Example request generated by analytics.js: /r/collect?v=1&_v=j79&a=212327327&t=pageview&_s=1&dl=https%3A%2F%2Fentity.works%2Fpatch%2F3-5-0&dp=%2Fpatch%2F3-5-0&ul=en-us&de=UTF-8&dt=3.5.0%20%7C%20Dead%20by%20Daylight%20Patch%20Notes&sd=24-bit&sr=1920x1080&vp=1914x977&je=0&_u=AACAAAAB~&jid=528079133&gjid=1818038270&cid=657204604.1578488495&tid=UA-154709538-3&_gid=966938712.1579475361&_r=1&z=1804482608
    // Contains properties:
    // v, v_, t, _s, dl, ul, de, dt, sd, sr, vp, je, _u, jid, gjid, cid, tid, _gid, _r, z
    const analyticsPayload = {
      uip: ip,
      ...context.query,
    }
    console.log(`${ip} [${Object.keys(analyticsPayload).join(", ")}]`)
    context.assert(analyticsPayload.tid, 400, "No tid given")
    const analyticsHeader = {}
    if (context.header["user-agent"]) {
      analyticsHeader["User-Agent"] = context.header["user-agent"]
    }
    got.post(argv.targetUrl, {
      headers: analyticsHeader,
      body: queryString.stringify(analyticsPayload),
    }).catch(error => {
      console.error(error)
    })
    context.status = 200
  })
  koa.listen(argv.port)
}

/**
 * @type {import("yargs").CommandBuilder}
 */
const builder = {
  port: {
    type: "number",
    default: 80,
    alias: "p",
    description: "Listening port",
  },
  targetUrl: {
    type: "string",
    default: "https://www.google-analytics.com/collect",
    alias: "t",
    description: "Target URL",
  },
}

yargs
  .scriptName(_PKG_NAME)
  .version(_PKG_VERSION)
  .command("$0", _PKG_DESCRIPTION, builder, job).argv